services:
  db:
    image: mysql:9.3
    restart: always
    environment:
      MYSQL_DATABASE: "autota"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./database:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uuser", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile.prod
    environment:
      DB_USER: "user"
      DB_PASSWORD: "password"
      DB_HOST: "db"
      DB_NAME: "autota"
      DB_PORT: "3306"
      FLASK_DEBUG: "False"
      TABOT_DIR: "/tabot-files"
      AUTH_URL: "http://host.docker.internal:4000/"
    ports:
      - "127.0.0.1:8009:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./backend:/app"
      - "./tabot-files:/tabot-files"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    volumes:
      - "./frontend:/app"
    ports:
      - "127.0.0.1:8008:3000"
    depends_on:
      - backend